//
//  LoginRouter.swift
//  DesafioSantander
//
//  Created by Israel Alves Santos Junior on 05/07/19.
//  Copyright (c) 2019 Israel Alves Santos Junior. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeTosegueSceneAccountWithSegue(_ segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func routeTosegueSceneAccountWithSegue(_ segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationViewController = segue.destination as! StatementViewController
            var destinationDataStore = destinationViewController.router!.dataStore!
            
            sendAccountInformation(source: dataStore!, destination: &destinationDataStore)
        }
    }
    
    func navigateToExtractView(source: LoginViewController, destination: StatementViewController) {
        source.show(destination, sender: nil)
    }
    
    func sendAccountInformation(source: LoginDataStore, destination: inout StatementDataStore) {
        destination.userAccount = source.userAccount
    }
}
