//
//  LoginModels.swift
//  DesafioSantander
//
//  Created by Israel Alves Santos Junior on 05/07/19.
//  Copyright (c) 2019 Israel Alves Santos Junior. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Login: Codable {
    var userAccount: UserAccount?
    var error: Error?
    
    struct UserAccount: Codable {
        var userId: Int = 0
        var name: String?
        var agency: String?
        var bankAccount: String?
        var balance: Double?
        
        
    }
    
    struct Error: Codable {
        var message: String?
    }
}
