//
//  LoginPresenter.swift
//  DesafioSantander
//
//  Created by Israel Alves Santos Junior on 05/07/19.
//  Copyright (c) 2019 Israel Alves Santos Junior. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentSomething(response: Login.Something.Response)
    func showCustomAlert(with: String)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login.Something.Response)
  {
    let viewModel = Login.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func showCustomAlert(with: String) {
        
        var message: UIAlertController! = nil
        var textAlert = ""
        var textTitleAlert = ""
        
        switch with {
        case "buttonLogin":
            textTitleAlert = "Falha no Login"
            textAlert = "Dados de Login Incorretos."
            
        case "buttonInfo":
            textTitleAlert = "Informação"
            textAlert = "Digite seu E-Mail ou CPF."
            
        default:
            print("Valor Default identifica Sucesso")
        }
        
        message = UIAlertController(title: textTitleAlert, message: textAlert, preferredStyle: .alert)
        
        message!.addAction(UIAlertAction(title: NSLocalizedString("OK", comment: "Default action"), style: .default, handler: { _ in
            NSLog("The \"OK\" alert occured.")}))
        
        viewController?.failure(alertController: message)
    }

}
