//
//  LoginWorker.swift
//  DesafioSantander
//
//  Created by Israel Alves Santos Junior on 05/07/19.
//  Copyright (c) 2019 Israel Alves Santos Junior. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class LoginWorker {
    
    let ud = UserDefaults.standard
    
    func doSomeWork() {
      
    }
    
    func saveUserDefault(button: UISwitch, user: UITextField) {

        if !button.isOn {
            user.text = nil
        }

        ud.set(user.text, forKey: "user")
        ud.set(button.isOn, forKey: "saveUser")

    }

    func loadUserDefault() -> String {
        return self.ud.string(forKey: "user") ?? ""
    }
    
    func loadUserDefaultBool() -> Bool {
        print("Carregamento do switch é: \(self.ud.bool(forKey: "saveUser"))")
        return self.ud.bool(forKey: "saveUser")
    }
    
    
}
