////
////  UserModels.swift
////  DesafioSantander
////
////  Created by Israel Alves Santos Junior on 05/07/19.
////  Copyright (c) 2019 Israel Alves Santos Junior. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//import UIKit
//
//enum UserModels
//{
//  // MARK: Use cases
//  
//  enum Something
//  {
//    struct Request
//    {
//    }
//    struct Response
//    {
//    }
//    struct ViewModel
//    {
//    }
//  }
//}
